### ISSUE TITLE
gulpsmith conflict with metalsmith redirect

### ISSUE THREAD

**Issue by anthonyjfio** [aymericbeaumet/metalsmith-redirect#10]
When I use `metalsmith-redirect` with `gulpsmith` I get the output below. 

```
[19:34:46] Using gulpfile ~/website-gulpsmith/gulpfile.js
[19:34:46] Starting 'metalsmith'...
[19:34:46] Finished 'metalsmith' after 82 ms
/home/user/website-gulpsmith/node_modules/gulpsmith/node_modules/vinyl/index.js:110
      throw new Error("File.contents can only be a Buffer, a Stream, or null.");
      ^

Error: File.contents can only be a Buffer, a Stream, or null.
    at File.Object.defineProperty.set (/home/user/website-gulpsmith/node_modules/gulpsmith/node_modules/vinyl/index.js:110:13)
    at new File (/home/user/website-gulpsmith/node_modules/gulpsmith/node_modules/vinyl/index.js:25:17)
    at Function.gulpsmith.to_vinyl (/home/user/website-gulpsmith/node_modules/gulpsmith/gulpsmith.js:211:18)
    at /home/user/website-gulpsmith/node_modules/gulpsmith/gulpsmith.js:124:43
    at Metalsmith.<anonymous> (/home/user/website-gulpsmith/node_modules/gulpsmith/gulpsmith.js:127:17)
    at Immediate._onImmediate (/home/user/website-gulpsmith/node_modules/co/index.js:52:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```

When I comment out the code pertaining to `metalsmith-redirect` in my `gulpfile` I don't get the error above.  Anyways, see my `gulpfile` below:

```
var gulp = require('gulp'),
    gFrontMatter = require('gulp-front-matter'),
    assign = require('lodash.assign'),
    M = require('gulpsmith'),
    ig = require('metalsmith-ignore'),
    md = require('metalsmith-markdown'),
    col = require('metalsmith-collections'),
    pag = require('metalsmith-pagination'),
    snip = require('metalsmith-snippet'),
    per = require('metalsmith-permalinks'),
    lay = require('metalsmith-layouts'),
    red = require('metalsmith-redirect'),
    moment = require('moment'),
    pkg = require('./package.json');

gulp.task('metalsmith', function() {
  gulp.src('./src/**/*')
    .pipe(gFrontMatter())
      .on('data', function(file) {
        assign(file, file.frontMatter);
        delete file.frontMatter;
      })
    .pipe(
      M()
        .use(ig([
          'css/*.css',
          'js/*.js'
        ]))
        .use(md())
        .use(col({
          blog: {
            pattern: './blog/*.md',
            sortBy: 'date',
            reverse: true
          },
          latest: {
            pattern: './blog/*.md',
            sortBy: 'date',
            reverse: true,
            limit: 10
          }
        }))
        .use(pag({
          'collections.blog': {
            perPage: 5,
            first: 'blog/index.html',
            layout: 'pagination.jade',
            path: 'blog/:num/index.html'
          }
        }))
        .use(snip({ maxLength: 300 }))
        .use(per({ relative: false }))
        .use(lay({
          engine: 'jade',
          moment: moment,
          pkg: pkg
        }))
        .use(red({
          '/github'   : 'https://github.com/anthonyjfio',
          '/gitlab'   : 'https://gitlab.com/u/anthonyjfio',
          '/bitbucket': 'https://bitbucket.com/anthonyjfio',
          '/twitter'  : 'https://twitter.com/anthonyjfio',
          '/snapchat' : 'https://www.snapchat.com/add/anthonyjfio'
        }))
    )
    .pipe(gulp.dest('./dist'))
})
```
Thank you!

**Comment by aymericbeaumet** [comment]
Thanks for noticing, this should now be fixed with 2.1.0
